theme = "hugo-tanka"
baseURL = "https://mlr-blog.netlify.com/"
languageCode = "en-us"
title = "mlr blog"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

enableEmoji = true
hasCJKLanguage = true

disqusShortname = "mlr-org-blog"

disable_mathjax = false

[params]
  sitename = "mlr blog"

[[menu.main]]
    name = "Home"
    url = "https://mlr-blog.netlify.com/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/mlr-org/mlr"
    weight = 2
[[menu.main]]
    name = "Authors"
    url = "https://github.com/mlr-org/mlr/wiki/Misc#mlr-developer-team-and-contributors-page"
    weight = 3
[[menu.main]]
    name = "mlr-tutorial"
    url = "https://mlr-org.github.io/mlr/"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
